export enum Position_E {
  FinancialAnalyst = "Финансовый аналитик",
  Businessman = "Предприниматель",
  ProductDesigner = "Продуктовый дизайнер",
  ProjectManager = "Менеджер проекта",
  FinancialManager = "Финансовый менеджер",
  BossFinanceDepartment = "Руководитель финансового департамента компании",
  ProductAnalyst = "Продуктовый аналитик",
  BossFinancialProduct = "Руководитель финансового продукта",
  MarketingManager = "Менеджер по маркетингу",
  DigitalTransformationManager = "Менеджер по цифровой трансформации",
}

export enum Skills_E {
  Excel = "Excel",
  SQL = "SQL",
  VBA = "VBA",
  C1 = "1С",
  PowerBI = "Power BI",
  Figma = "Figma",
  Sketch = "Sketch",
  Illustrator = "Illustrator",
  Photoshop = "Photoshop",
  Principle = "Principle",
  Tilda = "Tilda",
  Python = "Python",
  GoogleAnalytics = "Google Analytics",
  YandexMetrics = "Яндекс Метрика",
  Shopify = "Shopify",
  Protopie = "Protopie",
  Cinema4D = "Cinema 4D",
  Visio = "Visio",
  BPMN = "BPMN",
  HQL = "HQL",
  Tableau = "Tableau",
  R = "R",
  MachineLearning = "Machine learning",
  GoogleAds = "Google Ads",
  Ahrefs = "Ahrefs",
  Pest = "Главред",
  MyTarget = "My Target",
  Xenu = "Xenu",
}
